### ISSUE TITLE
CSS get loaded on front-end, when using the $config->styles

### ISSUE THREAD

**Issue by somatonic** [Notanotherdotcom/AdminTemplateColumns#3]
This module shouldn't be autoload or the css shouldn't be added if on front end. When using something like the Spex module, it will throw errors.

**Comment by somatonic** [comment]
Well the error seems how Spex or AIOM is handling those styles... But the problem that backend scripts/styles get added to front-end $config->styles array, could be avoided by using autoload => "template=admin"

**Comment by Notanotherdotcom** [comment]
I was looking for that one line of code for a while and you'd already found it - I should have known :)

**Comment by Notanotherdotcom** [comment]
Updated the code - thanks again.
